// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// ...import 'package:firebase_core/firebase_core.dart';

// ...

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-bm1LfO_MIFHwCK3dDilxeqy02qDhlDw',
    appId: '1:1089396595354:web:38e0dfca0cd6a51f34dd23',
    messagingSenderId: '1089396595354',
    projectId: 'vot-pickle-ball',
    authDomain: 'vot-pickle-ball.firebaseapp.com',
    storageBucket: 'vot-pickle-ball.firebasestorage.app',
    measurementId: 'G-YQ9BSCP6SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk8WAJLtUDN05GPZnQjimv9ohpdSPtwNc',
    appId: '1:1089396595354:android:143cc90d2d0dcdb234dd23',
    messagingSenderId: '1089396595354',
    projectId: 'vot-pickle-ball',
    storageBucket: 'vot-pickle-ball.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr12xdEYcyrJb2xAHuVY9vZqQf3VIu284',
    appId: '1:1089396595354:ios:db820f53c5a85c1334dd23',
    messagingSenderId: '1089396595354',
    projectId: 'vot-pickle-ball',
    storageBucket: 'vot-pickle-ball.firebasestorage.app',
    iosBundleId: 'com.example.votPickleBall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr12xdEYcyrJb2xAHuVY9vZqQf3VIu284',
    appId: '1:1089396595354:ios:db820f53c5a85c1334dd23',
    messagingSenderId: '1089396595354',
    projectId: 'vot-pickle-ball',
    storageBucket: 'vot-pickle-ball.firebasestorage.app',
    iosBundleId: 'com.example.votPickleBall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-bm1LfO_MIFHwCK3dDilxeqy02qDhlDw',
    appId: '1:1089396595354:web:18218b7f9aa873b034dd23',
    messagingSenderId: '1089396595354',
    projectId: 'vot-pickle-ball',
    authDomain: 'vot-pickle-ball.firebaseapp.com',
    storageBucket: 'vot-pickle-ball.firebasestorage.app',
    measurementId: 'G-R5YWL6TFCF',
  );
}
